/**
 * Registry manifest — the copy-paste half of the hybrid model.
 *
 * The same `packages/core/src` files are shipped two ways:
 *   1. compiled, as the `@abek/awesome-ui` npm package
 *   2. as source, through this registry
 *
 * Output conforms to the shadcn registry-item schema, so consumers install with
 * the shadcn CLI and no CLI of our own:
 *
 *   npx shadcn@latest add https://<host>/r/button.json
 */

export interface RegistryItem {
  name: string;
  type: "registry:ui" | "registry:lib" | "registry:hook" | "registry:style";
  title: string;
  description: string;
  /** Paths relative to `packages/core/src`. */
  files: string[];
  /** Other registry items this one needs. Resolved recursively by the CLI. */
  registryDependencies?: string[];
  /** npm packages the consumer must install. */
  dependencies?: string[];
  cssVars?: boolean;
}

export const registry: RegistryItem[] = [
  {
    name: "utils",
    type: "registry:lib",
    title: "Utils",
    description: "Class-name joiner, ref/handler composition, and the variant resolver.",
    files: [
      "utils/cn.ts",
      "utils/composeEventHandlers.ts",
      "utils/composeRefs.ts",
      "utils/variants.ts",
    ],
  },
  {
    name: "types",
    type: "registry:lib",
    title: "Polymorphic types",
    description: "Type helpers for `as` and `asChild` components.",
    files: ["types/polymorphic.ts"],
  },
  {
    name: "tokens",
    type: "registry:style",
    title: "Design tokens",
    description: "CSS custom properties for color, space, radius, type, and motion.",
    files: ["styles/base.css"],
    cssVars: true,
  },
  {
    name: "slot",
    type: "registry:ui",
    title: "Slot",
    description: "Renders its only child with merged props — the engine behind `asChild`.",
    files: ["primitives/Slot/Slot.tsx", "primitives/Slot/index.ts"],
    registryDependencies: ["utils"],
  },
  {
    name: "portal",
    type: "registry:ui",
    title: "Portal",
    description: "SSR-safe portal that mounts after hydration.",
    files: ["primitives/Portal/Portal.tsx", "primitives/Portal/index.ts"],
    registryDependencies: ["use-isomorphic-layout-effect"],
  },
  {
    name: "visually-hidden",
    type: "registry:ui",
    title: "VisuallyHidden",
    description: "Screen-reader-only text.",
    files: [
      "primitives/VisuallyHidden/VisuallyHidden.tsx",
      "primitives/VisuallyHidden/VisuallyHidden.module.css",
      "primitives/VisuallyHidden/index.ts",
    ],
    registryDependencies: ["utils"],
  },
  {
    name: "use-controllable-state",
    type: "registry:hook",
    title: "useControllableState",
    description: "One hook covering controlled and uncontrolled props.",
    files: ["hooks/useControllableState.ts"],
  },
  {
    name: "use-disclosure",
    type: "registry:hook",
    title: "useDisclosure",
    description: "Open/close state for overlays.",
    files: ["hooks/useDisclosure.ts"],
    registryDependencies: ["use-controllable-state"],
  },
  {
    name: "use-id",
    type: "registry:hook",
    title: "useId",
    description: "SSR-safe id with a caller override, for ARIA wiring.",
    files: ["hooks/useId.ts"],
  },
  {
    name: "use-isomorphic-layout-effect",
    type: "registry:hook",
    title: "useIsomorphicLayoutEffect",
    description: "`useLayoutEffect` in the browser, `useEffect` on the server.",
    files: ["hooks/useIsomorphicLayoutEffect.ts"],
  },
  {
    name: "theme",
    type: "registry:ui",
    title: "ThemeProvider",
    description: "Light/dark/system color scheme with no-flash first paint.",
    files: ["theme/ThemeProvider.tsx", "theme/index.ts"],
    registryDependencies: ["tokens"],
  },
  {
    name: "button",
    type: "registry:ui",
    title: "Button",
    description: "Button with six variants, three sizes, loading state, and `asChild`.",
    files: [
      "components/Button/Button.tsx",
      "components/Button/Button.module.css",
      "components/Button/Button.types.ts",
      "components/Button/Button.variants.ts",
      "components/Button/index.ts",
    ],
    registryDependencies: ["utils", "types", "slot", "visually-hidden", "tokens"],
  },
  {
    name: "input",
    type: "registry:ui",
    title: "Input",
    description: "Text input with label, description, and error wired for assistive tech.",
    files: [
      "components/Input/Input.tsx",
      "components/Input/Input.module.css",
      "components/Input/Input.types.ts",
      "components/Input/Input.variants.ts",
      "components/Input/index.ts",
    ],
    registryDependencies: ["utils", "use-id", "tokens"],
  },
  {
    name: "use-focus-trap",
    type: "registry:hook",
    title: "useFocusTrap",
    description: "Keeps Tab cycling inside a container while active.",
    files: ["hooks/useFocusTrap.ts", "utils/tabbable.ts"],
  },
  {
    name: "use-scroll-lock",
    type: "registry:hook",
    title: "useScrollLock",
    description: "Reference-counted background scroll lock.",
    files: ["hooks/useScrollLock.ts"],
    registryDependencies: ["use-isomorphic-layout-effect"],
  },
  {
    name: "use-floating",
    type: "registry:hook",
    title: "useFloating",
    description: "Anchored positioning with flip, shift, and arrow tracking.",
    files: ["hooks/useFloating.ts", "utils/position.ts"],
  },
  {
    name: "dismissable-layer",
    type: "registry:ui",
    title: "DismissableLayer",
    description: "Escape and outside-press dismissal, stacked so only the top layer reacts.",
    files: [
      "primitives/DismissableLayer/DismissableLayer.tsx",
      "primitives/DismissableLayer/layerStack.ts",
      "primitives/DismissableLayer/index.ts",
    ],
    registryDependencies: ["utils"],
  },
  {
    name: "presence",
    type: "registry:ui",
    title: "usePresence",
    description: "Defers unmount until the exit animation finishes.",
    files: ["primitives/Presence/Presence.tsx", "primitives/Presence/index.ts"],
    registryDependencies: ["use-isomorphic-layout-effect"],
  },
  {
    name: "dialog",
    type: "registry:ui",
    title: "Dialog",
    description: "Modal dialog with focus trap, scroll lock, and layered dismissal.",
    files: [
      "components/Dialog/Dialog.tsx",
      "components/Dialog/Dialog.module.css",
      "components/Dialog/Dialog.types.ts",
      "components/Dialog/DialogContext.ts",
      "components/Dialog/index.ts",
    ],
    registryDependencies: [
      "utils",
      "types",
      "slot",
      "portal",
      "presence",
      "dismissable-layer",
      "use-disclosure",
      "use-focus-trap",
      "use-scroll-lock",
      "use-id",
      "tokens",
    ],
  },
  {
    name: "popover",
    type: "registry:ui",
    title: "Popover",
    description: "Anchored popover with flip, shift, and an arrow that tracks the trigger.",
    files: [
      "components/Popover/Popover.tsx",
      "components/Popover/Popover.module.css",
      "components/Popover/Popover.types.ts",
      "components/Popover/PopoverContext.ts",
      "components/Popover/index.ts",
    ],
    registryDependencies: [
      "utils",
      "types",
      "slot",
      "portal",
      "presence",
      "dismissable-layer",
      "use-disclosure",
      "use-floating",
      "use-focus-trap",
      "use-id",
      "tokens",
    ],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    title: "Tooltip",
    description: "Hover and focus tooltip with open/close delays and Escape dismissal.",
    files: [
      "components/Tooltip/Tooltip.tsx",
      "components/Tooltip/Tooltip.module.css",
      "components/Tooltip/Tooltip.types.ts",
      "components/Tooltip/index.ts",
    ],
    registryDependencies: [
      "utils",
      "types",
      "slot",
      "portal",
      "presence",
      "use-controllable-state",
      "use-floating",
      "use-id",
      "tokens",
    ],
  },
  {
    name: "toast",
    type: "registry:ui",
    title: "Toast",
    description:
      "Notification queue with an imperative API, pausing timers, and swipe-to-dismiss.",
    files: [
      "components/Toast/Toaster.tsx",
      "components/Toast/Toast.module.css",
      "components/Toast/Toast.types.ts",
      "components/Toast/ToastIcon.tsx",
      "components/Toast/toast.ts",
      "components/Toast/toastStore.ts",
      "components/Toast/useToast.ts",
      "components/Toast/index.ts",
    ],
    registryDependencies: ["utils", "portal", "presence", "tokens"],
  },
  {
    name: "use-field",
    type: "registry:hook",
    title: "useField",
    description: "Shared label, description and error wiring for form controls.",
    files: ["hooks/useField.ts"],
    registryDependencies: ["use-id"],
  },
  {
    name: "spinner",
    type: "registry:ui",
    title: "Spinner",
    description: "Busy indicator that announces itself, or stays silent when decorative.",
    files: [
      "components/Spinner/Spinner.tsx",
      "components/Spinner/Spinner.module.css",
      "components/Spinner/Spinner.types.ts",
      "components/Spinner/index.ts",
    ],
    registryDependencies: ["utils", "visually-hidden", "tokens"],
  },
  {
    name: "badge",
    type: "registry:ui",
    title: "Badge",
    description: "Status pill with three variants, five tones, and an optional dot.",
    files: [
      "components/Badge/Badge.tsx",
      "components/Badge/Badge.module.css",
      "components/Badge/Badge.types.ts",
      "components/Badge/Badge.variants.ts",
      "components/Badge/index.ts",
    ],
    registryDependencies: ["utils", "types", "slot", "visually-hidden", "tokens"],
  },
  {
    name: "card",
    type: "registry:ui",
    title: "Card",
    description: "Surface with header, media, body and footer sections.",
    files: [
      "components/Card/Card.tsx",
      "components/Card/Card.module.css",
      "components/Card/Card.types.ts",
      "components/Card/index.ts",
    ],
    registryDependencies: ["utils", "types", "slot", "tokens"],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    title: "Checkbox",
    description: "Checkbox with indeterminate state over a real input.",
    files: [
      "components/Checkbox/Checkbox.tsx",
      "components/Checkbox/Checkbox.module.css",
      "components/Checkbox/Checkbox.types.ts",
      "components/Checkbox/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "use-field", "tokens"],
  },
  {
    name: "switch",
    type: "registry:ui",
    title: "Switch",
    description: "On/off control using role=switch over a real input.",
    files: [
      "components/Switch/Switch.tsx",
      "components/Switch/Switch.module.css",
      "components/Switch/Switch.types.ts",
      "components/Switch/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "use-field", "tokens"],
  },
  {
    name: "use-roving-focus",
    type: "registry:hook",
    title: "useRovingFocus",
    description: "Arrow-key navigation over a collection, moving real DOM focus.",
    files: ["hooks/useRovingFocus.ts"],
  },
  {
    name: "use-typeahead",
    type: "registry:hook",
    title: "useTypeahead",
    description: "Type-to-jump over a collection, with repeat-key cycling.",
    files: ["hooks/useTypeahead.ts"],
  },
  {
    name: "select",
    type: "registry:ui",
    title: "Select",
    description:
      "Select-only combobox with roving focus, typeahead, and form participation.",
    files: [
      "components/Select/Select.tsx",
      "components/Select/Select.module.css",
      "components/Select/Select.types.ts",
      "components/Select/SelectContext.ts",
      "components/Select/index.ts",
    ],
    registryDependencies: [
      "utils",
      "portal",
      "presence",
      "dismissable-layer",
      "use-controllable-state",
      "use-disclosure",
      "use-field",
      "use-floating",
      "use-id",
      "use-roving-focus",
      "use-typeahead",
      "tokens",
    ],
  },
  {
    name: "radio-group",
    type: "registry:ui",
    title: "RadioGroup",
    description: "Radio group over native inputs, so the browser owns arrow navigation.",
    files: [
      "components/RadioGroup/RadioGroup.tsx",
      "components/RadioGroup/RadioGroup.module.css",
      "components/RadioGroup/RadioGroup.types.ts",
      "components/RadioGroup/RadioGroupContext.ts",
      "components/RadioGroup/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "use-field", "use-id", "tokens"],
  },
  {
    name: "tabs",
    type: "registry:ui",
    title: "Tabs",
    description: "Tabs with automatic or manual activation and either orientation.",
    files: [
      "components/Tabs/Tabs.tsx",
      "components/Tabs/Tabs.module.css",
      "components/Tabs/Tabs.types.ts",
      "components/Tabs/TabsContext.ts",
      "components/Tabs/index.ts",
    ],
    registryDependencies: [
      "utils",
      "use-controllable-state",
      "use-id",
      "use-roving-focus",
      "tokens",
    ],
  },
  {
    name: "menu",
    type: "registry:ui",
    title: "Menu",
    description: "Dropdown menu with roving focus, typeahead, and toggle items.",
    files: [
      "components/Menu/Menu.tsx",
      "components/Menu/Menu.module.css",
      "components/Menu/Menu.types.ts",
      "components/Menu/MenuContext.ts",
      "components/Menu/index.ts",
    ],
    registryDependencies: [
      "utils",
      "types",
      "slot",
      "portal",
      "presence",
      "dismissable-layer",
      "use-disclosure",
      "use-floating",
      "use-id",
      "use-roving-focus",
      "use-typeahead",
      "tokens",
    ],
  },
  {
    name: "accordion",
    type: "registry:ui",
    title: "Accordion",
    description: "Accordion with single or multiple open panels and animated height.",
    files: [
      "components/Accordion/Accordion.tsx",
      "components/Accordion/Accordion.module.css",
      "components/Accordion/Accordion.types.ts",
      "components/Accordion/AccordionContext.ts",
      "components/Accordion/index.ts",
    ],
    registryDependencies: [
      "utils",
      "presence",
      "use-controllable-state",
      "use-id",
      "use-roving-focus",
      "tokens",
    ],
  },
  {
    name: "avatar",
    type: "registry:ui",
    title: "Avatar",
    description: "Avatar with initials fallback, deterministic tint, status dot, and stacking.",
    files: [
      "components/Avatar/Avatar.tsx",
      "components/Avatar/Avatar.module.css",
      "components/Avatar/Avatar.types.ts",
      "components/Avatar/index.ts",
    ],
    registryDependencies: ["utils", "visually-hidden", "tokens"],
  },
  {
    name: "separator",
    type: "registry:ui",
    title: "Separator",
    description: "Rule with optional label, decorative or structural.",
    files: [
      "components/Separator/Separator.tsx",
      "components/Separator/Separator.module.css",
      "components/Separator/Separator.types.ts",
      "components/Separator/index.ts",
    ],
    registryDependencies: ["utils", "tokens"],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    title: "Skeleton",
    description: "Loading placeholder, hidden from assistive tech.",
    files: [
      "components/Skeleton/Skeleton.tsx",
      "components/Skeleton/Skeleton.module.css",
      "components/Skeleton/Skeleton.types.ts",
      "components/Skeleton/index.ts",
    ],
    registryDependencies: ["utils", "tokens"],
  },
  {
    name: "progress",
    type: "registry:ui",
    title: "Progress",
    description: "Determinate and indeterminate progress bar.",
    files: [
      "components/Progress/Progress.tsx",
      "components/Progress/Progress.module.css",
      "components/Progress/Progress.types.ts",
      "components/Progress/index.ts",
    ],
    registryDependencies: ["utils", "use-id", "tokens"],
  },
  {
    name: "alert",
    type: "registry:ui",
    title: "Alert",
    description: "Inline status message with tones and optional live announcement.",
    files: [
      "components/Alert/Alert.tsx",
      "components/Alert/Alert.module.css",
      "components/Alert/Alert.types.ts",
      "components/Alert/index.ts",
    ],
    registryDependencies: ["utils", "tokens"],
  },
  {
    name: "textarea",
    type: "registry:ui",
    title: "Textarea",
    description: "Multi-line input with auto-resize and a character count.",
    files: [
      "components/Textarea/Textarea.tsx",
      "components/Textarea/Textarea.module.css",
      "components/Textarea/Textarea.types.ts",
      "components/Textarea/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "use-field", "tokens"],
  },
  {
    name: "slider",
    type: "registry:ui",
    title: "Slider",
    description: "Single and range slider with pointer, keyboard and step snapping.",
    files: [
      "components/Slider/Slider.tsx",
      "components/Slider/Slider.module.css",
      "components/Slider/Slider.types.ts",
      "components/Slider/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "use-id", "tokens"],
  },
  {
    name: "pagination-range",
    type: "registry:lib",
    title: "getPaginationRange",
    description: "Which page numbers to show, and where the ellipses go.",
    files: ["utils/pagination.ts"],
  },
  {
    name: "collapsible",
    type: "registry:ui",
    title: "Collapsible",
    description: "Single disclosure with animated height.",
    files: [
      "components/Collapsible/Collapsible.tsx",
      "components/Collapsible/Collapsible.module.css",
      "components/Collapsible/Collapsible.types.ts",
      "components/Collapsible/index.ts",
    ],
    registryDependencies: ["utils", "types", "slot", "presence", "use-disclosure", "use-id", "tokens"],
  },
  {
    name: "toggle",
    type: "registry:ui",
    title: "Toggle",
    description: "Button that stays pressed, standalone or in a group.",
    files: [
      "components/Toggle/Toggle.tsx",
      "components/Toggle/Toggle.module.css",
      "components/Toggle/Toggle.types.ts",
      "components/Toggle/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "toggle-group", "tokens"],
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    title: "ToggleGroup",
    description: "Shared selection across a set of toggles.",
    files: [
      "components/ToggleGroup/ToggleGroup.tsx",
      "components/ToggleGroup/ToggleGroupContext.ts",
      "components/ToggleGroup/ToggleGroup.types.ts",
      "components/ToggleGroup/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "use-roving-focus", "tokens"],
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    title: "Breadcrumb",
    description: "Navigation trail with decorative separators.",
    files: [
      "components/Breadcrumb/Breadcrumb.tsx",
      "components/Breadcrumb/Breadcrumb.module.css",
      "components/Breadcrumb/Breadcrumb.types.ts",
      "components/Breadcrumb/index.ts",
    ],
    registryDependencies: ["utils", "types", "slot", "visually-hidden", "tokens"],
  },
  {
    name: "pagination",
    type: "registry:ui",
    title: "Pagination",
    description: "Page controls with a constant-width truncated range.",
    files: [
      "components/Pagination/Pagination.tsx",
      "components/Pagination/Pagination.module.css",
      "components/Pagination/Pagination.types.ts",
      "components/Pagination/index.ts",
    ],
    registryDependencies: ["utils", "use-controllable-state", "visually-hidden", "tokens"],
  },
  {
    name: "drawer",
    type: "registry:ui",
    title: "Drawer",
    description: "Dialog anchored to an edge of the viewport.",
    files: [
      "components/Drawer/Drawer.tsx",
      "components/Drawer/Drawer.module.css",
      "components/Drawer/Drawer.types.ts",
      "components/Drawer/index.ts",
    ],
    registryDependencies: ["utils", "types", "slot", "portal", "presence", "dismissable-layer", "use-disclosure", "use-focus-trap", "use-scroll-lock", "use-id", "tokens"],
  },
  {
    name: "alert-dialog",
    type: "registry:ui",
    title: "AlertDialog",
    description: "Confirmation dialog that demands an explicit choice.",
    files: [
      "components/AlertDialog/AlertDialog.tsx",
      "components/AlertDialog/AlertDialog.types.ts",
      "components/AlertDialog/index.ts",
    ],
    registryDependencies: ["dialog"],
  },
];
